# Generated by Django 5.2.3 on 2025-06-20 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu')),
                ('message_type', models.CharField(choices=[('complaint', 'Şikayet'), ('request', 'Talep'), ('general', 'Genel'), ('support', 'Destek')], default='general', max_length=20, verbose_name='Mesaj Tipi')),
                ('content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('status', models.CharField(choices=[('new', 'Yeni'), ('read', 'Okundu'), ('replied', 'Cevaplandı'), ('closed', 'Kapalı')], default='new', max_length=20, verbose_name='Durum')),
                ('is_read_by_recipient', models.BooleanField(default=False, verbose_name='Alıcı Tarafından Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='İlgili Sipariş')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Yanıt İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yanıt Tarihi')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messages_app.message', verbose_name='Mesaj')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Mesaj Yanıtı',
                'verbose_name_plural': 'Mesaj Yanıtları',
                'ordering': ['created_at'],
            },
        ),
    ]
