# Generated by Django 5.2.3 on 2025-06-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Firma Adı')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon Numarası')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta Adresi')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='İlgili Kişi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Depo Adı')),
                ('address', models.TextField(verbose_name='Depo Adresi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Depo',
                'verbose_name_plural': 'Depolar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Ürün Kodu')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('current_stock', models.IntegerField(default=0, verbose_name='Mevcut Stok')),
                ('minimum_stock', models.IntegerField(default=0, verbose_name='Minimum Stok (Kritik Seviye)')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Maliyet (TL)')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı (TL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Ürün Görseli')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ürün Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Satışa Açık (Aktif)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.category', verbose_name='Kategori')),
                ('main_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_products', to='stock.supplier', verbose_name='Ana Tedarikçi')),
                ('warehouse_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stock.warehouse', verbose_name='Depo Konumu')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
    ]
