# Generated by Django 5.2.3 on 2025-06-20 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Açık Tema'), ('dark', 'Koyu Tema'), ('blue', 'Mavi Tema'), ('green', 'Yeşil Tema')], default='light', max_length=20, verbose_name='Tema')),
                ('navbar_position', models.CharField(choices=[('top', 'Üst Navbar'), ('side', 'Yan Sidebar')], default='top', max_length=10, verbose_name='Navbar Konumu')),
                ('auto_logout_minutes', models.IntegerField(default=30, verbose_name='Otomatik Çıkış Süresi (dk)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Tercihi',
                'verbose_name_plural': 'Kullanıcı Tercihleri',
            },
        ),
    ]
