# Generated by Django 5.2.3 on 2025-06-20 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Bildirim Mesajı')),
                ('notification_type', models.CharField(choices=[('order_status', 'Sipariş Durumu Değişikliği'), ('debt_change', 'Borç Durumu Değişikliği'), ('stock_alert', 'Stok Uyarısı'), ('new_message', 'Yeni Mesaj'), ('system_alert', 'Sistem Uyarısı')], max_length=50, verbose_name='Bildirim Tipi')),
                ('related_object_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='İlgili Obje ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlgili Obje Tipi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
    ]
